### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by qqq6771020** [Sara0201Tao/2022HPC#1]
您好，我想向您请教下2022HPC目录下EpiMalignant_NMF.R文件中第30行中ToReExpr函数应该加载什么R包才可以使用，目前将EpiMalignant_NMF.R文件中所有R包均已加载，但未能使用ToReExpr函数。所以想请教您如何解决这个问题。
谢谢！

**Comment by Sara0201Tao** [comment]
感谢关注。

ToReExpr函数是自己编写的函数，参考了另一篇计算肿瘤细胞NMF gene modules的文章（https://doi.org/10.1038/s41422-020-00402-8）。以下函数供参考:

ToReExpr <- function(Raw.matrix, NoNeg = TRUE, clock_inter = 2000){
  genesN <- nrow(Raw.matrix)
  ReExpr.matrix <- Raw.matrix
  for (i in 1:genesN){
    if (i %% clock_inter == 0){print(i)}
    ReExpr.matrix[i,] <- Raw.matrix[i,] - mean(Raw.matrix[i,])
  }
  if (NoNeg == TRUE){
    ReExpr.matrix[ReExpr.matrix < 0] <- 0
  }
  return(ReExpr.matrix)
}

**Comment by qqq6771020** [comment]
您好,谢谢老师的回复; 在使用您这个代码中发现Convert2Genes函数也无法加载,所以想请教您可以将这个EpiMalignant_NMF.R文件中相关的函数(如Convert2Genes函数)发给我学习一下嘛?非常感谢
